# Generated by Django 5.2.7 on 2025-11-08 13:16

import cflows.models.car
import cflows.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_organization_organization_role_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('color', models.CharField(default='Not specified', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=cflows.utils.car_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('station_fields', models.JSONField(blank=True, default=cflows.models.car.get_default_station_fields, help_text='Custom station fields for the car.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('custom_car_info', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('default_status', models.CharField(default='pending', max_length=100)),
                ('allowed_statuses', models.JSONField(default=list)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_configurations', to='accounts.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
