# Generated by Django 5.2.7 on 2025-11-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_remove_account_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_role_members',
            field=models.JSONField(default=dict, help_text='Mapping of organization roles to member IDs'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_roles',
            field=models.JSONField(default=dict, help_text='Define roles and permissions for organization members'),
        ),
        migrations.AlterField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='accounts.organization', verbose_name='Connecting Organisation'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Member Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'unique_together': {('organization', 'member')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='member_organizations', through='accounts.OrganizationMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
