# Generated by Django 5.2.7 on 2025-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_organization_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_role_members',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of organization roles to member IDs', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_roles',
            field=models.JSONField(blank=True, default=dict, help_text='Define roles and permissions for organization members', null=True),
        ),
    ]
